all:
	gcc -pthread ../Utils/src/string_utils.c ../Utils/src/file_utils.c src/string_search.c src/naiv/main.c -o string_search_n.exe
	gcc -pthread ../Utils/src/string_utils.c ../Utils/src/file_utils.c src/string_search.c src/KMP/main.c -o string_search_kmp.exe